### ISSUE TITLE
[EXAMPLE-BUG] Creator not showing on mobile devices

### ISSUE THREAD

**Issue by CanCodes** [Discord-Templates/Bugs-and-Feedbacks#1]
_Reported By: Ping#1000 (548547460276944906)_

**Describe the bug**
Creator part of the template page is not showing on mobile devices

**To Reproduce**
1. Go to the website
2. Click on a template
3. Scroll down to creator part
4. Observe

**Expected behavior**
Should be able to see who created this template

**Screenshots**
![image](https://cdn.discordapp.com/attachments/717110203023360081/717259493855199252/Screenshot_20200602-091247_Chrome_Canary.jpg)

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser: stock browser

**Comment by eggsy** [comment]
Already fixed, will be on production when I push changes.
