### ISSUE TITLE
[BUG] After navigating to another page, dropdown remains selected

### ISSUE THREAD

**Issue by kaanrkaraman** [Discord-Templates/Bugs-and-Feedbacks#10]
**Describe the bug**
After navigating to another page, dropdown remains selected.

**To Reproduce**
1. Open "More" dropdown.
2. Click on something.
3. Then click something other than the thing you've clicked.

**Expected behavior**
When you'll apply my steps, you'll see that dropdown remains open and selected in navigation bar.

**Screenshots**
http://snowy.is-online.me/i/mj1rfyiuxazff5r.gif

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 83.0.4103.61

**Comment by heyimnitho** [comment]
CR on [OS] macOS Catalina 10.15.4, [Browser] Opera GX, Ver: 68.0.3618.142

**Comment by eggsy** [comment]
Fixed.
