### ISSUE TITLE
[BUG] Broken error messages

### ISSUE THREAD

**Issue by kaanrkaraman** [Discord-Templates/Bugs-and-Feedbacks#11]
**Describe the bug**
Error messages are broken.

**To Reproduce**
1. Navigate to a page that doesn't exist, e.g. https://discordtemplates.com/legal/privacy
2. See error.

**Expected behavior**
We should see a proper error message.

**Screenshots**
http://snowy.is-online.me/i/hqruvlm5ok0fpoj.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.61

**Comment by eggsy** [comment]
A page that doesn't exist -> 404 -> not found. 
This seems pretty correct to me.

**Comment by heyimnitho** [comment]
I think he's talking about this sentence on 404 page: `{"message":"Not Found","statusCode":404}`

**Comment by eggsy** [comment]
That's not a "message". It's the actual error returned from page, we call them :tada: J :tada: S :tada: O :tada: N. Helps us identify errors easily.

**Comment by kaanrkaraman** [comment]
OK then.

**Comment by CanCodes** [comment]
Shortly, Privacy and FAQ pages are not in the website right now. this also closes #12

**Comment by eggsy** [comment]
_There are no links to those pages on website._
