### ISSUE TITLE
[BUG] Incorrect status URL in footer

### ISSUE THREAD

**Issue by kaanrkaraman** [Discord-Templates/Bugs-and-Feedbacks#14]
**Describe the bug**
There is a link for system status but it is incorrect, hoping that you add it soon 😎 

**To Reproduce**
1. Scroll bottom and see footer.
2. Click "System Status"

**Comment by heyimnitho** [comment]
Not a bug, same thread as #12 to this ticket.

**Comment by CanCodes** [comment]
It is actually not a bug, we are waiting for our DNS service to redirect it to https://discordtemplates.statuspage.io/
But thanks for pointing this out!
