### ISSUE TITLE
[BUG] Nothing Template

### ISSUE THREAD

**Issue by kaanmutlus** [Discord-Templates/Bugs-and-Feedbacks#15]
I can create a template without a channel, category or role. I think this should be fixed.
https://i.imgur.com/n7StGHQ.png

**Comment by kaanmutlu17** [comment]
Ama benim template'im hatıra kalsın pls :)

**Comment by eggsy** [comment]
Fixed, try adding the same template again and check if you get any errors.

**Comment by kaanmutlus** [comment]
Added again gentleman.

**Comment by kaanmutlus** [comment]
Fixed, thank you.
