### ISSUE TITLE
[BUG] Immediately clicked button remains selected after changing the theme

### ISSUE THREAD

**Issue by kaanrkaraman** [Discord-Templates/Bugs-and-Feedbacks#16]
**Describe the bug**
After clicking the change theme button, I immediately click to button where my username writes and that button remains selected after theme is changed. Also see the additional context for additional bugs.

**To Reproduce**
1. Click "Change Theme" button.
2. Then immediately click the button right next to it.
3. You'll see that the button remains selected.

**Screenshots**
http://snowy.is-online.me/i/x2o52aej5jdrr8j.gif

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.61

**Additional Context**
Also, right click your username, open Dev Tools and click this button here: http://snowy.is-online.me/i/om2thzol6od5n5e.png
When you navigate to that page, you'll see that the button where your username is still remains selected.

**Comment by kaanrkaraman** [comment]
For those who'll say that's normal and no bug, try this with another page. You'll see that you cannot go to your user profile when theme is being changed.

**Comment by eri** [comment]
The user profile button will remain selected as you go to the specified page - the theme changes in less than a second, depending of your browser if you try to click on another link during this second of theme change, your browser might ignore it.

The site is accessible after the successfull theme change.
