### ISSUE TITLE
[BUG] Unsufficient height

### ISSUE THREAD

**Issue by kaanrkaraman** [Discord-Templates/Bugs-and-Feedbacks#18]
**Describe the bug**
Footer is not in bottom on a page.

**To Reproduce**
1. Select "Tags" from navigation bar.
2. See bottom.

**Expected behavior**
It should be in bottom 🤔 

**Screenshots**
http://snowy.is-online.me/i/cpi0tugmwgr6w07.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.61

**Additional context**
Actually I'm not pretty sure that this is a bug, still, I just wanted to inform you about how it looks -bad-.

**Comment by eggsy** [comment]
Is this your actual screen size or did you zoom out?

**Comment by eggsy** [comment]
Got the answer from Discord and fixed ✅
