### ISSUE TITLE
[FEATURE] Increase character limit

### ISSUE THREAD

**Issue by enxg** [Discord-Templates/Bugs-and-Feedbacks#2]
**Is your feature request related to a problem? Please describe.**
Yes, I need to explain my template but the 1000 character limit is not enough.

**Describe the feature you'd like**
Increasing character limit. It can be 1500 or 2000 characters. The first 1000 characters are displayed, press "read more" to see the rest.

**Comment by eggsy** [comment]
why do you need such a high limit?

**Comment by enxg** [comment]
> why do you need such a high limit?

1000 is not enough

**Comment by eri** [comment]
This isn't a valid reason - We decided to keep the max description length at 1 000 chars as templates should only be focused on the global content of templates. We don't think that there is a need to put more details about all roles/channels as they are already displayed.

Maybe be more explicit regarding your feature request? Let us know if I'm missing some point. 👍

**Comment by enxg** [comment]
> This isn't a valid reason - We decided to keep the max description length at 1 000 chars as templates should only be focused on the global content of templates. We don't think that there is a need to put more details about all roles/channels as they are already displayed.
> 
> Maybe be more explicit regarding your feature request? Let us know if I'm missing some point.

It can be like roles. You see first 1000 characters, you click "read more", you see full description.

or add image support so we can use photos for roles/channels

**Comment by eggsy** [comment]
Please read more about "image adding ability" on [#4](https://github.com/Discord-Templates/Bugs-Feedbacks/issues/4#issuecomment-637687848) and we will monitor to see if people are going to need more space in long description.
