### ISSUE TITLE
[BUG] 'Go Back' button is clashing with the navbar.

### ISSUE THREAD

**Issue by heyimnitho** [Discord-Templates/Bugs-and-Feedbacks#20]
**Describe the bug**
When I editing my template and wanted to go back the template page, there's a little button bug happens when I pointed my mouse marker on 'Go Back' button.

**To Reproduce**
1. Go to your 'template' page
2. Click on 'Edit'
3. Point your marker on 'Go Back'
4. Observe

**Expected behavior**
It shouldn't be clashing with navbar when I pointed my marker on 'Go Back' button.

**Screenshots**
[In Website](https://thisisnithy.is-inside.me/JnBMCmct.png)

**Desktop (please complete the following information):**
 - OS: MacBook Air 2017, macOS Catalina 10.15.4
 - Browser: Opera GX
 - Version: 68.0.3618.142

**Comment by eggsy** [comment]
Wdym? Navbar is always on top of all elements, this seems fine.

**Comment by heyimnitho** [comment]
Yeah but try it, navigation bar and button are clashing. I showed this on my screenshot.

**Comment by eggsy** [comment]
That's not when you scroll down a bit?

**Comment by heyimnitho** [comment]
Nope, when I pointed my marker onto button it happens.

**Comment by eggsy** [comment]
Position is totally fine for me and I don't think it's a browser related issue, tried CTRL + F5?

![image](https://user-images.githubusercontent.com/13917975/83795301-ec27c500-a6a7-11ea-950e-972f53ae87ed.png)

**Comment by heyimnitho** [comment]
Yeah, seems like browser related bug. [Look here!](https://thisisnithy.is-inside.me/21j8Dso0.png)

**Comment by eggsy** [comment]
Tried in private mode? Maybe it's cached that once... Opera uses same technologies as Chrome so it shouldn't really differ from each other.

**Comment by heyimnitho** [comment]
Well, same issue happens on [private mode](https://thisisnithy.is-inside.me/5USPWO5E.png).

**Comment by eggsy** [comment]
Weird, can't really help about it right now but we'll continue investigating this issue on Discord. Thanks.
