### ISSUE TITLE
[FEATURE] A few feedbacks for a more beautiful design. #1

### ISSUE THREAD

**Issue by alfredsaveron** [Discord-Templates/Bugs-and-Feedbacks#21]
**Describe the Feature Request.**
A few feedbacks for a more beautiful design. 

**Feature Requests**

- New profile badges.
- New awesome tags ( Template Tags )
- New list showing template usage numbers ( Top 10 Usage )
- Verified Templates
- List of Templates verified by discordtemplates.com

**Additional Message**
These features will be useful for everyone, we will have a better Discord Templates if done..

**Thanks , Alf**

**Comment by CanCodes** [comment]
You have to be more specific for the badges and tags, what exactly are you looking for? Also we already have verified templates on our website and the full listing is on it's way to be published soon.

**Comment by alfredsaveron** [comment]
Badges = Supporter , Verified Owner , Partner , Helper and more..
Tags = Fun , Stream , Social , Twitch , Youtube and more..
