### ISSUE TITLE
[FEATURE] A mini suggestion for the more section in the website.

### ISSUE THREAD

**Issue by cagoshian** [Discord-Templates/Bugs-and-Feedbacks#22]
**Is your feature request related to a problem? Please describe.**
Yes, I'm always confusing when I open "more" menu, because the menu background is almostly same with the website background.

**Describe the feature you'd like**
It will be better if you make the "more" menu background color to #2b2b2b. 

**Additional context**
Also, button backgrounds isn't changing when you hover in Firefox.

**Comment by CanCodes** [comment]
_NOTE: Button backgrounds do change on Firefox, It's just not changing when hovered over one of the buttons in "more" menu._

**Comment by cagoshian** [comment]
> 
> 
> _NOTE: Button backgrounds do change on Firefox, It's just not changing when hovered over one of the buttons in "more" menu._

https://gyazo.com/42d2d3f12005609f60a16c26c6d2c4d0
Only in "more" menu, yes.

**Comment by eggsy** [comment]
Seems like an issue with JavaScript events in Firefox. I don't think we can really fix this, closing this for now.
