### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by GrkmDgn** [Discord-Templates/Bugs-and-Feedbacks#25]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
Can featured templates support language feature? It’s not necesarry but it would be great if you can make it.

**Additional context**
![7AA3BFD8-A138-421B-B6BF-B30DBABB6766](https://user-images.githubusercontent.com/44582592/103454556-6f6cd000-4cf6-11eb-8175-6fa09d1f2279.jpeg)

**Comment by eri** [comment]
There is no point in translating the descriptions of featured templates as their contents (channels and roles) will all be staying in their primary language.

We will have more featured templates in the future, the list will be a subject to change (too frequently). 

In addition to that, template descriptions are supposed to be an user imput that can be modified at anytime by their creators, translating strings of this nature is definitively a no-no.
