### ISSUE TITLE
Sunucu Templerinin Emojileride Sunucuya Eklemesi

### ISSUE THREAD

**Issue by xFasters** [Discord-Templates/Bugs-and-Feedbacks#27]
Aldığımız Templerde kullanıcılar Emojiye Basınca Rol Alma - Rol Verme Gibi Sistem Yapıyorlar Bizde Tek Tek Emojileri Yüklesin Hatta şey Olabilir
t.emote-upload {Link} Gibi Yapabilirseniz Sevinirim Discord - Lowzy

**Comment by subnwa** [comment]
bence olması gereken bir şey.Birde sunucuda yani backup yaptığımız sunucuda duyuru kanalları vs gibi şeyleri aktarıyormu bilmiyorum ama öyle bir özellik yoksa güzel olur.
