### ISSUE TITLE
[BUG] Template description external link bug?!

### ISSUE THREAD

**Issue by alfredsaveron** [Discord-Templates/Bugs-and-Feedbacks#29]
**Describe the bug**
When I add an external link it doesn't work properly. **For example**: When I specify ``[Eri#1000](https://github.com/eri)`` it doesn't work properly.

**To Reproduce**
1. Go to ``https://discordtemplates.com/templates/template_link/edit``
2. Click ``LONG DESCRIPTION (?/1500)``
3. Add an external link like ``[Eri#1000](https://github.com/eri)`` and click Submit
4. Go back to the template page you edited and see the bug.

**Expected behavior**
The behavior that should be; it correctly points to the external link. Like this: [Eri#1000](https://github.com/eri)

**Screenshots**
Before: ``https://discordtemplates.com/templates/template_link/edit``

<img src="https://cdn.discordapp.com/attachments/745937151094423642/817093682229674014/unknown.png">

After: ``https://discordtemplates.com/templates/hTPFScfrQw9T``

<img src="https://cdn.discordapp.com/attachments/745937151094423642/817093807539093534/unknown.png">

**Desktop:**
 - Browser: [Google Chrome • New Tab]
 - Version: [Latest]
 
 **Live Bug:**
 [Here](https://discordtemplates.com/templates/hTPFScfrQw9T)

**Comment by eggsy** [comment]
Hi there, thank you for reporting this bug. I have investigated the issue and found your problem. Luckily, it's neither your nor the website's problem, it's just the sugar of markdown which doesn't allow HTML and MD without empty space between them. You can watch the GIF below and see how I fixed it. 

P.S. This is the current editor that's available on our website, so next time, you can really use it like this to preview how it's going to look on your page (but remember, we don't allow some HTML so they might not appear even if they are there in the preview).

I am closing this issue now.

![gif](https://user-images.githubusercontent.com/13917975/110134695-88d7da00-7d82-11eb-8594-c2f8f4a284bb.gif)
