### ISSUE TITLE
[FEATURE]  Adding pictures to the long description

### ISSUE THREAD

**Issue by enxg** [Discord-Templates/Bugs-and-Feedbacks#3]
**Is your feature request related to a problem? Please describe.**
I want to use photos in the description of my template.

**Describe the feature you'd like**
There is a button to add a picture. We press this button, we write the link of our picture. The picture in that link is added to the description.

**Comment by eggsy** [comment]
Please refer to [#4](https://github.com/Discord-Templates/Bugs-Feedbacks/issues/4#issuecomment-637687848) for more information on this.
