### ISSUE TITLE
[FEATURE] Custom Template Link

### ISSUE THREAD

**Issue by realmeric** [Discord-Templates/Bugs-and-Feedbacks#30]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the feature you'd like**
Custom link for verified or Popular templates like https://discordtemplates.com/tr/templates/chat31 and custom use code t.use chat31

**Additional context**
no

**Comment by CanCodes** [comment]
Hi @JIPrettyCool,
We already provide custom template links for our verified and partnered templates. If you want to have a custom template link, you either need to be a partner or be verified.
