### ISSUE TITLE
[FEATURE] Screenshots feature on Template page.

### ISSUE THREAD

**Issue by heyimnitho** [Discord-Templates/Bugs-and-Feedbacks#4]
It can be cool, when we can add screenshots about our server template or any show our template banner in webpage.

**Comment by eggsy** [comment]
We are still experimenting the website and we won't add image/video/iframe support (because it may lead to security problems) to website until we learn more on this.

**Comment by eri** [comment]
Agreed, this doesn't means that we won't add images or a banner, it can definitely something to think about in the future :)

**Comment by heyimnitho** [comment]
Oh, thanks for answering this thread.
