### ISSUE TITLE
[FEATURE] Multi Owners

### ISSUE THREAD

**Issue by enxg** [Discord-Templates/Bugs-and-Feedbacks#5]
**Describe the feature you'd like**
Add multi owner feature like DBL.  

> User A make a template.
> When adding template to website, adds User B as an owner to template.
> On templates page you see User A and User B are owners.

Sorry for bad England.

**Comment by realmeric** [comment]
why :D?

**Comment by enxg** [comment]
> why :D?

I make templates with my friend so I want to add he as an owner too.

**Comment by CanCodes** [comment]
We could add this in the future but it is likely that it will not be any time soon. Issue is not going to be closed, please consider voting 👍 if you would also want us to implement this to our services.

**Comment by eri** [comment]
Multiple template owners won't be something that will be implemented in the near future, as I don't think it'll be a relevant addition.
