### ISSUE TITLE
[FEATURE] A certification system -maybe-

### ISSUE THREAD

**Issue by kaanrkaraman** [Discord-Templates/Bugs-and-Feedbacks#6]
Certification system for templates that gets a certain number of upvotes monthly, and which is unique as an idea.

**Comment by heyimnitho** [comment]
Suggested before in my mega-feedback thread #1: https://thisisnithy.is-inside.me/sDywUHQ9.png

**Comment by CanCodes** [comment]
I know this thread is older than #8, but #8 is more detailed. Closing the thread.
