### ISSUE TITLE
[BUG] When I click "Movies" in index of discordtemplates.com, it redirecting to /tag/movies section.

### ISSUE THREAD

**Issue by heyimnitho** [Discord-Templates/Bugs-and-Feedbacks#7]
**Describe the bug**
It's not a bug actually, a small mistake happens in `index.vue` file.

**To Reproduce**
1. Open 'discordtemplates.com'
2. Click on 'Movies' button in index page.
3. Observe

**Expected behavior**
It should redirect to `/tag/movie` section in website.

**Screenshots**
https://thisisnithy.is-inside.me/C5eKsikk.png
https://thisisnithy.is-inside.me/k86zi6qD.png

**Desktop (please complete the following information):**
 - OS: MacBook Air 2017, macOS Catalina 10.15.4
 - Browser: Opera GX
 - Version: 68.0.3618.142

**Comment by CanCodes** [comment]
Nice catch

**Comment by eggsy** [comment]
fixed, give it 1 or 2 minutes to build.
