### ISSUE TITLE
[BUG] Small animation bug in "Partners" page

### ISSUE THREAD

**Issue by kaanrkaraman** [Discord-Templates/Bugs-and-Feedbacks#9]
**Describe the bug**
When the page loads, image loads up firstly, then when texts are sliding they go over the image.

**To Reproduce**
1. Go to partners page.
2. That's it ;)

**Expected behavior**
Animation has to correct, i guess 🤔.

**Screenshots**
http://snowy.is-online.me/i/50f0pswaid17oeq.gif

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.61

**Comment by eggsy** [comment]
probably not a bug, but will look into it later

**Comment by eggsy** [comment]
nope, it'll stay that way for now.
